#!/bin/sh

sudo -b ~/.scripts/kanata -c ~/.config/kanata/kanata.kbd > /dev/null 2>&1; 
sleep 2;
xset r rate 250 60;
setxkbmap -option caps:swapescape -option shift:both_capslock -option shift:both_capslock_cancel;

